image: Visual Studio 2022
build: off
max_jobs: 3

init:
  - git config --global core.autocrlf input

shallow_clone: true

environment:
   matrix:
    #  - py: Python37
    #  - py: Python37-x64
    #  - py: Python38
    #  - py: Python38-x64
    #  - py: Python39
    #  - py: Python39-x64
    #  - py: Python310
    #  - py: Python310-x64
    #  - py: Python311
     - py: Python311-x64

test_script:
   - C:\%py%\python.exe setup.py install
   - C:\%py%\Scripts\pip.exe uninstall comtypes -y
   - C:\%py%\python.exe test_pip_install.py
   - C:\%py%\python.exe -m unittest discover -v -s ./comtypes/test -t comtypes\test
